import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Header from "../components/header/Header";

const vazirMatn = Vazirmatn({
  variable: "--font-vazir-matn",
  subsets: ["arabic"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js">
      <body
        className={` ${vazirMatn.variable} antialiased text-default`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
